"""
spiral 08: deploy the landing page (locally + as static files).

quilt-trace produces self-contained HTML — any web server can serve it.
This spiral packages the rendered pages for deployment.
"""
import os
import shutil
import subprocess


def main():
    print("\n🌱 Spiral 08 — Deploy landing pages")
    print("=" * 60)

    site_dir = "/workspace/repos/quilt-director/site"
    if not os.path.exists(site_dir):
        print("  ✗ no site directory; run spiral 07 first")
        return 1

    # List what's there
    files = sorted(os.listdir(site_dir))
    print(f"  Site contents:")
    total = 0
    for f in files:
        path = os.path.join(site_dir, f)
        size = os.path.getsize(path)
        total += size
        print(f"    {size:>8,} bytes  {f}")
    print(f"    {'-'*30}")
    print(f"    {total:>8,} bytes  total ({len(files)} files)")

    # Create a simple index.html that links to all the pages
    index = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Quilt Organism — Fleet Landing</title>
<style>
  body { font-family: -apple-system, sans-serif; background: #0a0e14; color: #c5cdd9;
         max-width: 800px; margin: 40px auto; padding: 0 24px; line-height: 1.6; }
  h1 { color: #818cf8; font-weight: 500; }
  a { color: #818cf8; text-decoration: none; border-bottom: 1px dashed #818cf8; }
  a:hover { background: #1f2733; }
  .panel { background: #131820; border: 1px solid #1f2733; border-radius: 8px;
           padding: 20px; margin: 20px 0; }
  code { font-family: monospace; background: #1f2733; padding: 2px 6px; border-radius: 2px; }
  .stamp { color: #6c7a8c; font-size: 12px; }
</style>
</head>
<body>
<h1>🌱 Quilt Organism — Fleet Landing</h1>
<p>
  The substrate walker pattern, composed at fleet scale.
  Each page below is a self-contained HTML rendering of a chain of
  receipts, generated by <code>quilt-trace</code>.
</p>

<div class="panel">
  <h2 style="margin-top: 0;">Pages</h2>
  <ul>
    <li><a href="fleet-organism.html">fleet-organism.html</a> — the whole fleet, 37 receipts across 7 substrates (the main landing)</li>
    <li><a href="organism.html">organism.html</a> — quilt-optimization + quilt-organism demo (20 receipts)</li>
    <li><a href="jev-organism.html">jev-organism.html</a> — jev-quilt's 8 productive sessions (40 receipts)</li>
  </ul>
</div>

<div class="panel">
  <h2 style="margin-top: 0;">What is this?</h2>
  <p>
    A <strong>substrate walker</strong> is a piece of software that
    walks a substrate (a corpus, a problem, a fleet) and emits
    witness receipts as it goes. The witness chain links them all
    together. <code>quilt-trace</code> reads those receipts and
    renders them as a self-contained HTML page with a force-directed
    graph of the chain.
  </p>
  <p>
    The cells are alive. The tissues work. The organs compose.
    The organism sees itself.
  </p>
</div>

<div class="panel">
  <h2 style="margin-top: 0;">Repos</h2>
  <ul>
    <li><a href="https://github.com/SuperInstance/quilt-organism">quilt-organism</a> — the walker of corpora</li>
    <li><a href="https://github.com/SuperInstance/quilt-trace">quilt-trace</a> — the visualizer</li>
    <li><a href="https://github.com/SuperInstance/quilt-optimization">quilt-optimization</a> — cuOpt substrate</li>
    <li><a href="https://github.com/SuperInstance/quilt-seed">quilt-seed</a> — vessel + legalese + stations</li>
    <li><a href="https://github.com/SuperInstance/jev-quilt">jev-quilt</a> — JEV oracle as substrate</li>
    <li><a href="https://github.com/SuperInstance/ai-writings">ai-writings</a> — the canon corpus</li>
  </ul>
</div>

<p class="stamp">
  Generated by Mavis (the substrate walker), 2026-09-24.
  Built from accumulated wisdom. See <code>journal/</code> in quilt-director.
</p>
</body>
</html>
"""

    index_path = os.path.join(site_dir, "index.html")
    with open(index_path, "w") as f:
        f.write(index)

    print(f"\n  ✓ Created {index_path}")

    # If python3 -m http.server is available, start it briefly to verify
    # But this might hang — let's just verify file is readable
    print(f"\n  To deploy locally: python3 -m http.server 8765 --directory {site_dir}")
    print(f"  Then open http://localhost:8765 in a browser.")
    print(f"\n  To deploy to Cloudflare Pages: see docs/CF_DEPLOY.md")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
